### ISSUE TITLE
"npm run example" throws an error

### ISSUE THREAD

**Issue by moroshko** [vegetableman/react-modal-component#1]
When running `npm run example` I get the error below. What am I missing?

``` shell
$ npm run example

> react-modal-component@1.0.6 example /Users/mishamoroshko/react-modal-component
> beefy example/browser.js --live -- -t [reactify --es6] -t brfs


/Users/mishamoroshko/react-modal-component/node_modules/beefy/bin/beefy:13
    throw err
          ^
Error: Could not find a suitable bundler!
    at onglobals (/Users/mishamoroshko/react-modal-component/node_modules/beefy/lib/setup-bundlers.js:50:18)
    at /Users/mishamoroshko/react-modal-component/node_modules/beefy/node_modules/find-global-packages/index.js:40:25
    at Object.cb [as oncomplete] (fs.js:168:19)

npm ERR! react-modal-component@1.0.6 example: `beefy example/browser.js --live -- -t [reactify --es6] -t brfs`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the react-modal-component@1.0.6 example script.
npm ERR! This is most likely a problem with the react-modal-component package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     beefy example/browser.js --live -- -t [reactify --es6] -t brfs
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-modal-component
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.1.0
npm ERR! command "node" "/usr/local/bin/npm" "run" "example"
npm ERR! cwd /Users/mishamoroshko/react-modal-component
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/mishamoroshko/react-modal-component/npm-debug.log
npm ERR! not ok code 0
```

**Comment by vegetableman** [comment]
Missed adding brfs as one of the dependency. Have pushed the fixes. Could you try again?

**Comment by vegetableman** [comment]
The above error looks obscure. Let me know if it works.

**Comment by moroshko** [comment]
@vegetableman I pulled the latest master, but still get the same error. I think you have something installed globally on your machine that I don't have.

**Comment by vegetableman** [comment]
Thanks for testing it out @moroshko. Did a install on a fresh ec2 instance, found the bug. Added browserify to the dependency. Let me know if it works now.

**Comment by moroshko** [comment]
Thanks, it works now.
